
// This file was auto-generated by the framework. You can add data models or change the existing ones

type Key<T extends string | number> = T

export interface UserActivity {
    eventId: Key<string>;
    timestamp: string;
    userId: string;
    activity: string;
}

export interface ParsedActivity {
    eventId: Key<string>;
    timestamp: Date;
    userId: string;
    activity: string;
}

export interface ClickedActivity {
    eventId: Key<string>;
    timestamp: Date;
}

